line-length = 240
target-version = "py312"
extend-exclude = [".medrix-flow"]

[lint]
select = ["E", "F", "I", "UP"]
ignore = []

[lint.isort]
known-first-party = ["deerflow", "medrix_flow", "app"]

[format]
quote-style = "double"
indent-style = "space"
